### ISSUE TITLE
Another "Could not find process" issue

### ISSUE THREAD

**Issue by Gryfer** [veeenu/eldenring-practice-tool#73] opened 2024-01-06 17:34 UTC
What's infuriating at the moment is that I had it working, closed the game for an hour or so, then went to redo it and now absolutely nothing I do can seem to salvage this. Below is the process I've gone through:

I have not been able to get the official EAC bypass to work under any circumstances. I have steam_appid.txt. The only content in the file is `1245620` and nothing extraneous (no periods, spaces, apostrophes, anything). It is not steam_appid.txt.txt (as you can see below, my extensions are fully visible). Steam is closed, but double-clicking elden_ring.exe just makes an hourglass appear next to my cursor for a moment before disappearing (the same thing that happens anytime I try to launch a Steam game while Steam is closed).

![explorer_2WcnOjMa7s](https://github.com/veeenu/eldenring-practice-tool/assets/53091072/0ac1af4b-205a-4926-b620-49d0fcfcb9a4)

I tried the alternative method (renaming `start_protected_game.exe` to `start_protected_game_original.exe`, then duplicating `elden_ring.exe` and naming the duplicated version to `start_protected_game.exe` and launching the game through the faked `start_protected_game.exe`. That method actually worked! I played around like that for a few minutes and the mod worked pretty well.

Then I closed the game to deal with my kid for an hour or so and when I came back, absolutely nothing will work. I've restarted my PC. I've redone -- from scratch -- the official and alternative methods. Absolutely nothing I do can get beyond "Could not find process." I don't have an antivirus and, even if Windows Defender counts, it ran perfectly fine without editing it before the restart. I am completely stuck and have no idea what I could possibly do at this point.

Yes, I have Seamless Co-Op installed but the practice tool worked perfectly find with that installed earlier today.

If anyone can help, I'd be grateful.

**Comment by veeenu** [comment] 2024-01-06 23:46
Hi, I am not aware of what ways seamless coop alters the game and unfortunately can't offer support with other mods enabled.

Does the practice tool emit any log at all? If so, can you post it here?

The only EAC bypass method supported is the steam_appid.txt one. It looks like you executed it correctly but if the game keeps starting with EAC then the problem is in there somewhere. Again I can't rule out that other mods affect the process in some way.

I suggest you start with a clean, vanilla slate -- either from a fresh download of the game or from a [downpatch](https://soulsspeedruns.com/eldenring/downpatching).

**Comment by Gryfer** [comment] 2024-01-11 15:33
Since my original post, I've actually gone through the full cycle again. Got it working, used it a while, turned off PC, now it won't work again.

The tool does output a log. Here it is:  [ERPT Log.txt](https://github.com/veeenu/eldenring-practice-tool/files/13905050/ERPT.Log.txt)

System Specs: https://www.userbenchmark.com/UserRun/66966611

To be clear, EAC **isn't** launching. It's that I can't launch the game outside of Steam. I have to have Steam open. Once it's open, the launch does not start EAC. I went ahead and screen recorded my entire process: https://youtu.be/MH_AjVBavrA

In the video, I start by trying to show you that the intended EAC bypass is properly done, but the game won't launch. I only get a little hourglass icon for a moment.
After that, I open Steam (log-in process and everything), then launch ER which does launch successfully without EAC.
Once in game, I open my menu to show that I have been able to use the tool (all rememberances at level 9, two different types of crimson flasks, etc). Then I attempt to run the tool and the issue arises.

I'm really not sure what the issue is but it doesn't seem to be EAC and, as said before, I don't have antivirus unless Windows Defender counts and, even then, I was able to get it working twice. My intuition is that it isn't EAC or Seamless Coop but I can't say with extreme certainty.

**Comment by veeenu** [comment] 2024-01-11 17:04
Renaming the exe to `start_protected_game.exe` is not supported by the tool at the moment, and most likely never will be -- it's unnecessary.

As for what concerns opening the game with Steam closed: Elden Ring has clearly a complicated lifecycle that goes through Steam which the EAC bypass tampers with. I think it's totally reasonable that it may require the Steam service to be started, as it is Steam itself that processes the `steam_appid.txt`.

Does EAC get bypassed if you open Steam and double click `eldenring.exe`? In that case, does the tool work?

(Also, if you updated Elden Ring today and are running current patch there's a good chance the tool won't work anyway -- there was a new patch and I don't have an ETA for when I'll be able to look into it).

>as said before, I don't have antivirus unless Windows Defender counts

Windows Defender _absolutely_ counts. The fact that the tool worked once or twice with it activated might be pure luck. The one time I activated it to try it out, it would just delete the tool outright.

---
I am investigating a potential issue with one of my software dependencies, so I might push a new nightly release in the near future. I'd like to have you try it out if you didn't manage to solve your issues by then.

**Comment by Gryfer** [comment] 2024-01-11 18:13
>Does EAC get bypassed if you open Steam and double click `eldenring.exe`?

Yes.

>Also, if you updated Elden Ring today and are running current patch

The current version I'm running is App. Ver. 1.10.1 and Calibrations Ver. 1.10. That does appear to be the new patch which unfortunately may complicate things a bit.

Current Status:
- I've undone the renamed `start_protected_game.exe`. The files are now as originally set up. `eldenring.exe` is the proper game file and `start_protected_game.exe` is the proper EAC file. `steam_appid.txt` is still included with the proper ID.
- Opening Steam and launching the game through `eldenring.exe` does work. EAC is bypassed.
- Now, I'm no longer getting 'Could not find process'. Now I'm getting an effect where it appears as if the tool *should* be working, but nothing happens in-game (particularly, no menu that provides all of the effects of the tool). This is very possibly a new patch issue.
- Link: https://youtu.be/Zt4TeNhhuAw (Looks like everything's working! :) Except nothing shows up in game. :( Possibly a new patch issue but I don't know.)
- At the end I open the `.toml` to show that I haven't edited any of the hotkeys or buttons, just out of sake of completeness.

**Comment by veeenu** [comment] 2024-01-12 15:53
The fact that you are no longer getting `Could not find process` confirms that the current setup was the correct one all along -- the process is found and the DLL is injected successfully.

It is to be expected now that nothing shows up in game, as the tool is not recognizing the patch. Support for that will come hopefully this weekend if I have time. Stay tuned!

**Comment by veeenu** [comment] 2024-01-12 17:34
@Gryfer can you please give the [nightly](https://github.com/veeenu/eldenring-practice-tool/releases/tag/nightly) release a spin? Should work on the new patch.

**Comment by Gryfer** [comment] 2024-01-12 17:46
Will do!

**Comment by Gryfer** [comment] 2024-01-12 17:48
Will do! For the record, the link you provided is for a file that is `dsiii_practice_tool`. Is that correct?

**Comment by Gryfer** [comment] 2024-01-12 17:49
@veeenu Will do! For the record, the link you provided is for a file that is `dsiii_practice_tool`. Is that correct?

**Comment by veeenu** [comment] 2024-01-12 17:58
Oh, my -- no, it is not. 😂 Uploaded the wrong zip!
Should be fixed now. Thanks for pointing that out!

**Comment by Gryfer** [comment] 2024-01-12 18:23
Okay, now *this* one finally activated my Windows Defender. It got instantaneously mad and auto-deleted the file. It never cared with the last one.

But, it worked! And you probably now have access to all of my financial information.

**Comment by veeenu** [comment] 2024-01-12 18:27
Then I'll just grab a beer on you! 🍻 😂 
Glad it works!

**Closed** 2024-01-12 18:37 UTC
