### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by nianaiing** [veeenu/eldenring-practice-tool#21] opened 2022-05-11 09:47 UTC
[jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/8668685/jdsd_er_practice_tool.log)
I have been used this softwave for some time,When I open tool,The game exited immediately.
EAC bypassed and Antivirus software close.
Version:1.03.1(1.04.1)

**Comment by veeenu** [comment] 2022-05-12 09:44
Hi! Did I understand correctly that the tool used to work before, and it is not working anymore?

In that case: what CPU/GPU/operating system are you running the game and the tool on? Have you upgraded any drivers/software after which the tool stopped working?

**Comment by nianaiing** [comment] 2022-05-13 09:23
yep,the tool used to work before, and it is not working.
I’m Windows 10,RTX 3060 laptop,i7-11800H.
Actually,i find the NVIDIA Driver autoupdate the new version.I don't understand NVIDIA Driver will affect to run the tools.Then I installed a lower version.The tools can run when the game open and display the logo.But it dosen't run on the old version.

**Comment by veeenu** [comment] 2022-05-15 12:57
Not sure why that's the case unfortunately -- could be the combination of driver, gpu and DirectX12 version and I can't debug it unless I am able reproduce it myself. :(

**Comment by nianaiing** [comment] 2022-05-15 14:20
The tool can run only in 1.04 version,But It's enough for now.At least I don't need a lower version.
Thanks for your help.

**Comment by erptwl** [comment] 2022-05-22 13:07
I get the same error on my RTX 2080. Win 10 x64-bit v21H2
[jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/8749458/jdsd_er_practice_tool.log)

**Comment by veeenu** [comment] 2022-05-22 13:35
> I get the same error on my RTX 2080. Win 10 x64-bit v21H2

Have you tried reverting the drivers? I can't reproduce it on the latest drivers (RTX 3080).

**Comment by erptwl** [comment] 2022-05-23 07:09
I didn't try reverting, but I tried updating and my current driver is the game-ready v512.77

**Comment by veeenu** [comment] 2022-05-23 17:16
@erptwl two very similar cases in a very short amount of time makes me think there may be something off about my hooks, but I can't really dig into it unless I can reproduce it myself -- DirectX12's error codes are pretty obscure as it is, unfortunately. I may try to defensively adjust some things in the next release but I can't guarantee it'll work everywhere.

**Comment by erptwl** [comment] 2022-05-25 15:30
I just hope it'll resolve itself on a next driver or windows cumulative update. But thanks very much for taking the time to help. This is really the best tool out there as usual, even though I didn't get to try it yet. Keep up the good work.

**Comment by veeenu** [comment] 2022-05-26 17:40
@erptwl @nianaiing I am about to draft a patch release that is going to take care of some rendering issues (#17 and #23). I'm not 100% sure, but there may be a chance that it also addresses the issue you guys are having.

When it drops, could you guys please test it out? If that doesn't you could try setting `log_level = "TRACE"`, starting up the tool, and then uploading `jdsd_dsiii_practice_tool.log` here? Thank you 🙏

**Comment by erptwl** [comment] 2022-05-27 04:42
@veeenu Sure, I will test it out. Thanks for informing. You meant the jdsd_er_practice_tool.log , right?

**Comment by veeenu** [comment] 2022-05-27 05:00
Yes, sorry. The one I mentioned is from the DS3 tool 😁

**Comment by erptwl** [comment] 2022-05-28 14:31
Hey @veeenu, I've just tested the new release you posted 21 hours ago. Unfortunately, same result, however, I noticed a "Null command queue" error as well. Here is the log file: 
[jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/8791303/jdsd_er_practice_tool.log)

**Comment by veeenu** [comment] 2022-05-28 14:51
That `Null command queue` is sort of expected, depends on the ordering in which some hooked functions are called.
I found a way to access DX12 debug features which could yield more information, I'll consider posting a debug version over the next few days when I can.

**Comment by RolloRoundbottom** [comment] 2022-05-28 16:40
Same crash on start issue. Previous version didn't work for me either.
Windows 11 Pro 64, Nvidia RTX 3080, Ryzen 5900HX
[jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/8791483/jdsd_er_practice_tool.log)
[DxDiag.txt](https://github.com/veeenu/eldenring-practice-tool/files/8791485/DxDiag.txt)

**Comment by nianaiing** [comment] 2022-05-31 15:06
I'm sorry it took so long to reply you.
Unfortunately,The same problem is take on new version.This my log.
@erptwl @RolloRoundbottom you can try open the tools when the  BANDAINAMCO logo was appear.I don't know the method can be worked on other version,my version is v1.04.2
Hoping it will be help you.
[jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/8806339/jdsd_er_practice_tool.log)

**Comment by veeenu** [comment] 2022-06-12 14:40
@nianaiing @erptwl @RolloRoundbottom

I finally managed to compile a debug-enabled version of the practice tool, you can find it [here](https://github.com/veeenu/eldenring-practice-tool/releases/download/1.0.1/jdsd_er_practice_tool_debug.zip).
Follow [these instructions](
https://github.com/veeenu/eldenring-practice-tool#i-found-an-issue-what-do-i-do) to enable the DXGI Debug layer before running it. It should provide a very verbose `jdsd_er_practice_tool.log` file, which should hopefully give me a bit of insight into what is going on with this issue.

**Comment by veeenu** [comment] 2022-06-18 06:43
I didn't realize you'd need the optional feature turned on -- I assumed every Windows install had it already. Could you maybe try uninstalling the DirectX SDK first? It could be cloaking the feature. Then refer to [this](https://docs.microsoft.com/en-us/windows/uwp/gaming/use-the-directx-runtime-and-visual-studio-graphics-diagnostic-features) piece of documentation for installing the graphics tools via feature, I assume those should have DX12 support.

As an aside, I want to thank you guys for going through this troubleshooting with me. My view of what the possible issues are is conditioned by my setup; gathering more information is going to be very helpful to the people who may have this issue in the future, so thank you!

**Comment by veeenu** [comment] 2022-06-19 07:01
Oh, I may have released a wrong toml file then. It's not necessary to use the previous release, 1.0.2 supports DXGI debug without the need for a separate build. Make sure you have both `log_level="trace"` and `dxgi_debug=true` configured (if you don't have this, just add it below `log_level`). If `log_level` is `"info"`, the DXGI debug logs won't show up.

**Comment by veeenu** [comment] 2022-06-23 07:04
That's ok! A lot of verbosity is expected anyway, as it's a lot of stuff that's happening every frame.

```
11:20:29 [DEBUG] (3) hudhook::hooks::dx12: [DIQ] ID3D12CommandAllocator::<final-release>: A command allocator 0x0000023F8B355920:'Unnamed ID3D12CommandAllocator Object' is being reset before previous executions associated with the allocator have completed.
11:20:29 [DEBUG] (3) hudhook::hooks::dx12: [DIQ] ID3D12CommandQueue::ExecuteCommandLists: A command list, which writes to a swapchain back buffer, may only be executed on the command queue associated with that buffer. Swap Chain: 0x0000023F31BE5260:'Unnamed Object' - Swap Chain Buffer: 0x0000023F01F65B80:'Unnamed ID3D12Resource Object' - Swap Chain Buffer's Command Queue: 0x0000023F316FEFE0:'Unnamed ID3D12CommandQueue Object' - Attempted Execution Command Queue: 0x0000023F534FDA20:'Internal DXGI CommandQueue'
11:20:29 [DEBUG] (3) hudhook::hooks::dx12: [DIQ] ID3D12CommandQueue::ExecuteCommandLists: Command lists must have matching type to queue.
11:20:29 [DEBUG] (3) hudhook::hooks::dx12: [DIQ] ID3D12Device::RemoveDevice: Device removal has been triggered for the following reason (DXGI_ERROR_INVALID_CALL: There is strong evidence that the application has performed an illegal or undefined operation, and such a condition could not be returned to the application cleanly through a return code).
11:20:29 [TRACE] (3) hudhook::hooks::dx12: [lib\hudhook\hudhook\src\hooks\dx12.rs:171] IDXGISwapChain3::Present(IDXGISwapChain3(IUnknown(0x23f31be5260)), 1, 0) invoked
11:20:29 [TRACE] (3) hudhook::hooks::dx12: [lib\hudhook\hudhook\src\hooks\dx12.rs:442] Rendering started
11:20:29 [TRACE] (3) hudhook::hooks::dx12: [lib\hudhook\hudhook\src\hooks\dx12.rs:527] The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
```

At first blush, it looks like this sequence of logs describes the cause of the device removal. I do not know whether that `CommandQueue` is the one controlled by me or by the application, I assume it's the latter.

I did then notice something at the very end of the log:

```
11:20:41 [TRACE] (3) hudhook::hooks::dx12: [lib\hudhook\hudhook\src\hooks\dx12.rs:287] Leaving WndProc
11:20:41 [TRACE] (3) hudhook::hooks::dx12: [lib\hudhook\hudhook\src\hooks\dx12.rs:200] Entering WndProc 707d0 46 0 e2144ff000
11:20:41 [TRACE] (3) hudhook::hooks::dx12: [lib\hudhook\hudhook\src\hooks\dx12.rs:287] Leaving WndProc
11:20:41 [TRACE] (3) hudhook::hooks::dx12: [lib\hudhook\hudhook\src\hooks\dx12.rs:148] IDXGISwapChain3::ResizeBuffers invoked
``` 

`IDXGISwapChain3::ResizeBuffers` is invoked at the very end of the loading process, when the final window position and size is determined; until then, the game manipulates the window every few seconds and is generally unresponsive to mouse events.

Ever since the DS3 tool, hooking into the rendering loop before the game has fully started (i.e. it is in the main menu, responding to user commands) has more often than not resulted in crashes.

I thought I may have suggested this above, but turns out I didn't: have you tried waiting for the game to be fully loaded, possibly even staying in-game, before launching the tool?

**Comment by veeenu** [comment] 2022-06-26 21:04
@DingusWingus366 let's continue here!

I have inspected the logs and looks like we need _even more_ logs. The "main" error seems to happen in the same spot in all log files you guys have posted, but the reason was not made explicit (yet!).

From now on, I will be continuously publishing nightly releases [here](https://github.com/veeenu/eldenring-practice-tool/releases/tag/nightly) with incremental changes, so that we can add more and more and more logging until we figure out what is really happening.

Such is the life in DirectX land, the error reporting is terrible and split across one billion different paths but we have to make do with it.

I will ask you guys to download nightly as soon as it releases (it hasn't _just yet_ and it is automated) and post another log.

Again, thank you all!

**Comment by pablomz97** [comment] 2022-07-12 12:07
Coming from #27, Had a older GPU driver install, v472.84 and it was not working, updated to v516.59 and I am getting the exact same issue, if you want I can try some in between installations or a specific target if you have any.

**Comment by pablomz97** [comment] 2022-07-14 11:45
> That's not necessary, I'd say. This may be a long shot, but: is Windows up to date?

I did a Windows update and retried and sadly run into the same exact issue. No matter if I am in main menu or completely in game it ends up instantly crashing.

Thank again and good luck with it!

**Comment by veeenu** [comment] 2022-07-14 12:13
@pablomz97 @PrimordialMofu (and anyone else who can reproduce this issue)

A new nightly version is [currently building](https://github.com/veeenu/eldenring-practice-tool/actions).
I added more logging functions that could help me figure out the root of the issue.

Once that has completed, and you see the [nightly release has been updated](https://github.com/veeenu/eldenring-practice-tool/releases/tag/nightly), could you please give this a try and upload new logs?

It will definitely still crash, but there could be useful information in there.

Make sure to have DXGI debugging enabled and `log = "TRACE"` set.

Thank you!

**Comment by veeenu** [comment] 2022-07-14 13:43
Just pushed a [new nightly](https://github.com/veeenu/eldenring-practice-tool/releases/tag/nightly) (again, make sure that the [actions](https://github.com/veeenu/eldenring-practice-tool/actions) have completed before checking it out). It _should_ solve the issue for most of you guys who shared logs with the same data in them.

Will keep this issue open and wait for you guys to confirm this works.

Thanks to @pablomz97 for the help in figuring this out!

**Comment by PrimordialMofu** [comment] 2022-07-15 03:17
Here is the log from the new nightly. it does still crash, though I did see the UI for a split second.
[jdsd_er_practice_tool.zip](https://github.com/veeenu/eldenring-practice-tool/files/9117495/jdsd_er_practice_tool.zip)
.

**Comment by veeenu** [comment] 2022-07-15 06:55
> Here is the log from the new nightly. it does still crash, though I did see the UI for a split second.

That's progress! I see no DXGI debug logs though, those could help in your case. Have you [enabled the DXGI debug layer](https://github.com/veeenu/eldenring-practice-tool#i-found-an-issue-what-do-i-do)?

**Comment by PrimordialMofu** [comment] 2022-07-15 07:40
[jdsd_er_practice_tool (2).zip](https://github.com/veeenu/eldenring-practice-tool/files/9118892/jdsd_er_practice_tool.2.zip)
I accidently attacked it to Start_Protected_game.exe so it didnt trace at all. I fixed it, heres the actual log.

**Comment by veeenu** [comment] 2022-07-15 12:59
@PrimordialMofu this is a distinct problem from the one in this issue; let us continue on #26.

**Comment by veeenu** [comment] 2022-08-09 12:25
With the official release of [1.0.4](https://github.com/veeenu/eldenring-practice-tool/releases/tag/1.0.4), closing this issue as no further feedback was received.

**Closed by veeenu** 2022-08-09 12:25 UTC
Labels: bug
