### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by Horygor** [veeenu/eldenring-practice-tool#18] opened 2022-04-29 18:47 UTC
I launch Elden Ring then the practice tool
I see the overlay on Elden Ring
When I press a key to click continue the game crashes

App version 1.03.2
Calibration 1.03.3
EAC is disabled
NoLogoMod is installed

[jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/8593052/jdsd_er_practice_tool.log)

**Comment by veeenu** [comment] 2022-04-30 22:54
What operating system are you on? Do you have antivirus software installed?
Could you please try again with the `log = "DEBUG"` setting and paste the `jdsd_er_practice_tool.log` file?

**Comment by Horygor** [comment] 2022-05-01 09:22
I'm on Windows 10 Pro 64 bits. I only have Windows Defender and no other antivirus program.
[jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/8598611/jdsd_er_practice_tool.log)

**Comment by Horygor** [comment] 2022-05-01 09:33
I just excluded the folder where the tool is from my antivirus and now it works.
Thanks for the help \[T]/

**Comment by Horygor** [comment] 2022-05-01 09:48
Is this normal that the game is low on fps ?

**Comment by veeenu** [comment] 2022-05-01 16:50
Yeah antiviruses can hamper the tool's functioning as some of the techniques it uses are typically used by malware.

The tool has some minimal performance overhead but shouldn't impact fps in a significant way. Chance for fps drops is higher if the game is not already running fast enough. General performance improvements are planned, but it's always going to do some extra work on top of the game.

**Comment by Danzoui** [comment] 2022-05-04 15:08
OS: Windows 10 PRO (x64), 21h2, 19044.1415
Antivirus: None
Windows Defender: Deleted
Windows Firewall: Service disabled
UAC: Disabled (Admin account)
EAC: Disabled (steam_appid.txt)
Checked the local disks, everything is in order with them. The problem is only with this program.
Game Patch: 1.04.1 (1.04.2) (But the program crashes without running the game.)
The program crashes immediately after launch. Logs are not created (DEBUG enabled).
There are only system logs (eventvwr.msc).
[error1000.txt](https://github.com/veeenu/eldenring-practice-tool/files/8621670/error1000.txt)
[error1005.txt](https://github.com/veeenu/eldenring-practice-tool/files/8621672/error1005.txt)

**Comment by veeenu** [comment] 2022-05-04 18:37
> (But the program crashes without running the game.) 
> The program crashes immediately after launch. Logs are not created (DEBUG enabled). 

Thank you for your feedback. Could you try running the executabel from a `cmd.exe` window? You should be able to see the console messages (if any) that are printed by the injector. If the executable crashes without the game being open, that would be the place I'd expect to see an error, short of running the program inside of a debugger. The injector is pretty minimal, though, it only checks for updates via a HTTP request, finds the game window and remotely executes `LoadLibrary`.

**Comment by Danzoui** [comment] 2022-05-04 18:46
@veeenu Absolutely nothing
<details>
<summary>screen</summary>

![1](https://user-images.githubusercontent.com/61109303/166804476-6396ac06-bfd4-4a4d-9f55-de70a71ac2a2.png)
</details>

**Comment by veeenu** [comment] 2022-05-05 11:28
@Danzoui could you run that in a debugger, to assess where exactly it is stopping? There are no places where it could crash without emitting any output -- see [this](https://github.com/veeenu/eldenring-practice-tool/blob/main/practice-tool/src/main.rs) and [this](https://github.com/veeenu/hudhook/blob/d7bfa32522b34fc386dc7d6c72e0a83377527900/hudhook/src/inject.rs#L20). At the very minimum, log entries should be emitted before any `unsafe` code is run at all, and all unrecoverable errors in the rest of the code will panic and print a stack trace before safely exiting.

**Comment by Danzoui** [comment] 2022-05-05 12:02
@veeenu
I created checksums for files:
[crc.md5.txt](https://github.com/veeenu/eldenring-practice-tool/files/8630996/crc.md5.txt)
Are they correct?
A little later I will try to use the debugger.

**Comment by veeenu** [comment] 2022-05-05 12:33
Yes, checksums are correct. My next assumption is that the CPU may be unsupported, e.g. missing SSE/AVX or similar instruction sets -- not sure what the linker is doing under the hood, but that error could be related to that.

**Comment by Danzoui** [comment] 2022-05-06 14:44
@veeenu 
I compiled the program myself and miraculously it worked. But on startup it write this in the console:
<details>
<summary>screen</summary>

![1](https://user-images.githubusercontent.com/61109303/167151898-1ceea46b-6ec6-4d56-ab62-e91a0f451422.png)
</details>
When switching the game to full screen mode, it instantly freezes. Works only in windowed mode.

[jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/8641515/jdsd_er_practice_tool.log)

And how to run the program in the debugger? x64dbg suitable?
Launching the version from github:
<details>
<summary>screen</summary>

![2](https://user-images.githubusercontent.com/61109303/167152026-30aae7e4-428a-4a70-80f8-53ee1604bb76.png)
</details>

My CPU instructions:
x86, x86-64, MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, SSE4A, XOP, AVX, FMA, FMA4, AES

**Comment by veeenu** [comment] 2022-05-06 16:56
I have received reports of fullscreen not working properly but couldn't get to testing those. Try borderless windowed mode for now.

The fact that an artifact compiled on your machine works makes me even more confident on the binary compatibility issue. Not sure if it's necessarily related to instruction sets, though. Which Rust toolchain and Visual Studio version do you have installed?

**Comment by Danzoui** [comment] 2022-05-06 17:09
@veeenu
Rust 1.60.0
Visual Studio Enterprise 2019, 16.10.3

Is the Practice Tool compiled using Visual Studio?
Because I only used the command "cargo xtask dist".

**Comment by veeenu** [comment] 2022-05-06 19:48
VS is called indirectly as a build step. What does `rustup toolchain list` output?

**Comment by Danzoui** [comment] 2022-05-06 19:50
> VS is called indirectly as a build step. What does `rustup toolchain list` output?

`stable-x86_64-pc-windows-msvc (default)`
`nightly-x86_64-pc-windows-msvc`

**Comment by veeenu** [comment] 2022-05-07 12:14
That's the correct toolchain. I honestly don't know the reason for this binary incompatibility at this point.

**Comment by DingusWingus366** [comment] 2022-06-26 19:30
This is Dingus from discord, it looks I'm having the same problem as everyone else
[jdsd_er_practice_tool2.txt](https://github.com/veeenu/eldenring-practice-tool/files/8987349/jdsd_er_practice_tool2.txt)
.

**Comment by veeenu** [comment] 2022-06-26 20:33
Locking this issue as duplicate of #21; let us continue discussion over there!

**Closed by veeenu** 2022-06-26 20:33 UTC
Labels: bug, needs triage
